name: Release & Publish

on:
  push:
    tags:
      - "v*"   # Runs only when you push a version tag like v1.0.1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install

      # Build all packages using turbo
      - name: Build packages
        run: pnpm turbo run build

      # Publish markdown-converter
      - name: Publish @hamza865/markdown-converter
        run: pnpm publish --filter=@hamza865/markdown-converter --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish string-utils
      - name: Publish @hamza865/string-utils
        run: pnpm publish --filter=@hamza865/string-utils --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
